spring.datasource.url=jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.0.117)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=XE)))
spring.datasource.username=system
spring.datasource.password=mysecretpassword
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
