SELECT CURRENT_TIMESTAMP AS "CURRENT_TIMESTAMP", 
    'After Migration STARTED' AS "PROCESS", 
    sys_context('userenv','current_schema') AS "CURRENT_SCHEMA", 
    'COMPLETED' AS "STATUS", 
    SYS_CONTEXT('USERENV', 'NETWORK_PROTOCOL') AS "NETWORK_PROTOCOL" ,
    SYS_CONTEXT('USERENV', 'SESSION_USER') AS "DB_USERNAME",
    SYS_CONTEXT('USERENV', 'DB_NAME') AS "DB_NAME"
FROM dual;
